# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1993bdb9e6c90a516db6bc1ccf11e5e646a7915e079a40717432dd53cd6df976f061a4bfa49a38771808785977f60e63d12b96d575d599201135b7f7a125a67b

test:
  secret_key_base: 6a7d499a64e2149b9e7c7c6387d8955bbb0ab7e98d91ba93e2db910d943291cafc22afc34a7307aa7f212dcb0f2ed87a8430a001b89e39cfda30d56083475d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
